title: Justin Spidell
email: justintspidell@gmail.com
description: >-
tagline: "Excellence in all things"
baseurl: "" # the subpath of your site, e.g. /blog
url: "justinspidell.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jace1427
linkedin_username: justinspidell1427

# Build settings
theme: minima

plugins:
  - jekyll-toc
  - jekyll-feed

header_pages:
  - about.md
  - portfolio.md
